from typing import List, Dict, Any

class VectorStore:
    def upsert(self, points: List[Dict[str, Any]]) -> None: ...
    def query(self, query_vec: List[float], top_k: int, filter_by: Dict[str, Any]) -> List[Dict[str, Any]]: ...
    def delete_where(self, where: Dict[str, Any]) -> None: ...
